PROJECT_NAME = nfc_commission_receiver

TARGET ?= nrf52840-mesh
LIBDIR ?= $(CURDIR)/../..

SOURCE_FILES = \
	app-config.c \
	application.c \
	board.c \
	boot.c \
	net-status.c \
	nfc-if.c

include $(LIBDIR)/Makefile.include
