PROJECT_NAME = nfc_commission

TARGET ?= nrf52840ble-os
LIBDIR ?= $(CURDIR)/../../..

SOURCE_FILES = \
	app-config.c \
	application.c \
	board.c \
	boot.c \
	net-status.c \
	nfc-if.c

include $(LIBDIR)/Makefile.include
